apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: smoketests.katapult.org
spec:
  group: katapult.org
  scope: Namespaced
  names:
    kind: SmokeTest
    listKind: smoketestList
    plural: smoketests
    singular: smoketest
    shortNames:
      - st
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            spec:
              type: object
              properties:
                url:
                  type: string
                expectedResponseText:
                  type: string   
                retryIntervalSeconds:
                  type: integer
                maxRetries:
                  type: integer
                startDelaySeconds:
                  type: integer
                timeout:
                  type: integer
                showPageContent:
                  type: boolean

