apiVersion: katapult.org/v1alpha1
kind: SmokeTest
metadata:
  name: main-test
  namespace: smok
spec: 
  url: http://back.mytanzu.xyz/dogs
  expectedResponseText: Total
  retryIntervalSeconds: 1
  startDelaySeconds: 1
  showPageContent: true
  timeout: 10
  maxRetries: 2
    