---
apiVersion: v1
kind: ConfigMap
metadata:
  name: checker-wget-parameters-test  
data:
  URL: http://back.mytanzu.xyz/dogs
  EXPECTED_RESPONSE_TEXT: Total
  RETRY_INTERVAL_SECS: "2"
  START_DELAY_SECS: "4"
  SHOW_PAGE_CONTENT: "1"
  TIMEOUT: "10"
  SKIP: "0"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: smoke-tester-job  
spec:
  backoffLimit: 4  
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: checker
          image: docker.io/katapulted/checker-wget:0.0.1
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: checker-wget-parameters-test            
