---
apiVersion: v1
kind: ConfigMap
metadata:
  name: checker-wget-parameters-test
  namespace: default
data:
  URL: http://ihm-service.mydemo:80
  EXPECTED_RESPONSE_TEXT: Gui MicroPets
  RETRY_INTERVAL_SECS: "2"
  START_DELAY_SECS: "4"
  SHOW_PAGE_CONTENT: "1"
  TIMEOUT: "10"
  SKIP: "0"
---
apiVersion: v1
kind: Pod
metadata:
  name: katapult-checker
  namespace: default
spec:
  containers:
    - name: checker
      image: registry.local:5000/katapult/checker-wget:0.0.0
      imagePullPolicy: Always
      envFrom:
        - configMapRef:
            name: checker-wget-parameters-test            
