apiVersion: v1
kind: ConfigMap
metadata:
  name: checker-wget-parameters-test  
data:
  URL: http://back.mytanzu.benoit/dogs
  EXPECTED_RESPONSE_TEXT: BENOIT
  RETRY_INTERVAL_SECS: "2"
  START_DELAY_SECS: "4"
  SHOW_PAGE_CONTENT: "1"
  TIMEOUT: "10"
  SKIP: "0"