---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: smoketest-operator
  name: smoketest-operator-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: smoketest-operator-role-cluster
rules:  
  - apiGroups: [katapult.org]
    resources: [smoketests]
    verbs: [list, create, update, delete, patch, watch, get]
  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]  
  - apiGroups: ["",networking.k8s.io, app, extensions, batch]      
    resources: [configmaps,ingresses, services,deployments,secrets,replicasets,pods, jobs]    
    verbs: [list, create,update,delete,patch,watch,get]
  # Framework: admission webhook configuration management.
  - apiGroups: [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch] 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:  
  name: smoketest-operator-role-namespaced
rules:  
  - apiGroups: [katapult.org]
    resources: [smoketests]
    verbs: [list, create, update, delete, patch, watch, get]
  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]  
  - apiGroups: ["",networking.k8s.io, app, extensions, batch]      
    resources: [configmaps,ingresses, services,deployments,secrets,replicasets,pods, jobs]    
    verbs: [list, create,update,delete,patch,watch,get]
  # Framework: admission webhook configuration management.
  - apiGroups: [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch] 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: smoketest-operator-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: smoketest-operator-role-cluster
subjects:
  - kind: ServiceAccount
    name: smoketest-operator-account
    namespace: smoketest-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: smoketest-operator
  name: smoketest-operator-rolebinding-namespaced
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: smoketest-operator-role-namespaced
subjects:
  - kind: ServiceAccount
    name: smoketest-operator-account