#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smoketest-operator
  namespace: #@ data.values.NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: smoketest-operator
  template:
    metadata:
      labels:
        application: smoketest-operator
    spec:
      serviceAccountName: smoketest-operator-account
      containers:
      - name: operator
        image: ghcr.io/bmoussaud/smoketest-operator:0.2.0-dev
        imagePullPolicy: Always